source 'http://rubygems.nos.ncu.edu.tw'
gem 'rack-cors', :require => 'rack/cors'
gem 'rake'
gem 'rspec'
gem 'airborne'
gem 'grape'
gem 'grape-swagger', :git => 'https://github.com/ruby-grape/grape-swagger.git'
gem 'grape-entity'
gem 'grape_logging', git: 'https://github.com/aserafin/grape_logging.git'
gem 'activerecord'
gem 'grape-activerecord'
gem 'sqlite3'
